apiVersion: v2
name: phpldapadmin
description: phpLDAPadmin web-based LDAP administration tool.
type: application
version: 0.1.0
appVersion: "2.3.11"
home: https://github.com/leenooks/phpLDAPadmin
sources:
  - https://github.com/leenooks/phpLDAPadmin
keywords:
  - ldap
  - phpldapadmin
maintainers:
  - name: osixia
