{{- if and (not .Values.extraEnvSecret.existingSecret) .Values.extraEnvSecret.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.secretName" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.extraEnvSecret.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and (not .Values.bootstrapEnvSecret.existingSecret) .Values.bootstrapEnvSecret.env }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.bootstrapEnvSecretName" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.bootstrapEnvSecret.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
