{{- if and .Values.secret.create (not .Values.secret.existingSecret) .Values.secret.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.secretName" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
