{{- $replicationEnabled := eq (include "openldap.replicationEnabled" .) "true" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "openldap.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  {{- if $replicationEnabled }}
  podManagementPolicy: Parallel
  {{- end }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openldap.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "openldap.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: openldap-bootstrap
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --skip-process
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "openldap.fullname" . }}-env
            - secretRef:
                name: {{ include "openldap.fullname" . }}-bootstrap-secret
            {{- if .Values.bootstrapEnvSecret.existingSecret }}
            - secretRef:
                name: {{ .Values.bootstrapEnvSecret.existingSecret }}
            {{- else if .Values.bootstrapEnvSecret.env }}
            - secretRef:
                name: {{ include "openldap.bootstrapEnvSecretName" . }}
            {{- end }}
          {{- if or (and $replicationEnabled (not .Values.openldap.bootstrap.replication.hosts)) .Values.extraEnv }}
          env:
            {{- if and $replicationEnabled (not .Values.openldap.bootstrap.replication.hosts) }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HEADLESS_SERVICE_NAME
              value: {{ include "openldap.fullname" . }}-headless
            - name: OPENLDAP_URLS
              value: {{ include "openldap.podUrls" . | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: /etc/openldap/slapd.d
            - name: data
              mountPath: /var/lib/openldap/openldap-data
            - name: backups
              mountPath: /var/lib/openldap/openldap-backups
            {{- if not (empty .Values.tlsSecret.existingSecret) }}
            - name: tls
              mountPath: /container/services/openldap/assets/certs
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.customModulesVolume) }}
            - name: custom-modules
              mountPath: /container/services/openldap/assets/module
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.customSchemasVolume) }}
            - name: custom-schemas
              mountPath: /container/services/openldap/assets/schema
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.bootstrapCustomConfigLdifVolume) }}
            - name: bootstrap-custom-config-ldif
              mountPath: /container/services/openldap-bootstrap/assets/ldif/config/custom
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.bootstrapCustomDataLdifVolume) }}
            - name: bootstrap-custom-data-ldif
              mountPath: /container/services/openldap-bootstrap/assets/ldif/data/custom
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.openldap.preUpgrade.enabled }}
        - name: openldap-pre-upgrade
          image: "{{ include "openldap.preUpgradeImage" . }}"
          imagePullPolicy: {{ .Values.previousImage.pullPolicy }}
          args:
            - --exec
            - openldap-pre-upgrade
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "openldap.fullname" . }}-env
            - secretRef:
                name: {{ include "openldap.secretName" . }}
                optional: true
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: /etc/openldap/slapd.d
            - name: data
              mountPath: /var/lib/openldap/openldap-data
            - name: backups
              mountPath: /var/lib/openldap/openldap-backups
            {{- if not (empty .Values.tlsSecret.existingSecret) }}
            - name: tls
              mountPath: /container/services/openldap/assets/certs
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.customModulesVolume) }}
            - name: custom-modules
              mountPath: /container/services/openldap/assets/module
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.customSchemasVolume) }}
            - name: custom-schemas
              mountPath: /container/services/openldap/assets/schema
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
      containers:
        - name: openldap
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --skip
            - openldap-bootstrap
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if .Values.openldap.protocols.ldap.enabled }}
            - name: ldap
              containerPort: {{ .Values.openldap.protocols.ldap.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.openldap.protocols.ldaps.enabled }}
            - name: ldaps
              containerPort: {{ .Values.openldap.protocols.ldaps.port }}
              protocol: TCP
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "openldap.fullname" . }}-env
            - secretRef:
                name: {{ include "openldap.secretName" . }}
                optional: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HEADLESS_SERVICE_NAME
              value: {{ include "openldap.fullname" . }}-headless
            {{- if and $replicationEnabled (not .Values.openldap.bootstrap.replication.hosts) }}
            - name: OPENLDAP_URLS
              value: {{ include "openldap.podUrls" . | quote }}
            {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: /etc/openldap/slapd.d
            - name: data
              mountPath: /var/lib/openldap/openldap-data
            - name: backups
              mountPath: /var/lib/openldap/openldap-backups
            {{- if not (empty .Values.tlsSecret.existingSecret) }}
            - name: tls
              mountPath: /container/services/openldap/assets/certs
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.customModulesVolume) }}
            - name: custom-modules
              mountPath: /container/services/openldap/assets/module
              readOnly: true
            {{- end }}
            {{- if not (empty .Values.customSchemasVolume) }}
            - name: custom-schemas
              mountPath: /container/services/openldap/assets/schema
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if and $replicationEnabled .Values.podAntiAffinity.enabled }}
      affinity:
        {{- include "openldap.podAntiAffinity" . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (not (empty .Values.tlsSecret.existingSecret)) (not (empty .Values.customModulesVolume)) (not (empty .Values.customSchemasVolume)) (not (empty .Values.bootstrapCustomConfigLdifVolume)) (not (empty .Values.bootstrapCustomDataLdifVolume)) .Values.extraVolumes (not .Values.persistence.enabled) }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: conf
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: backups
          emptyDir: {}
        {{- end }}
        {{- if not (empty .Values.tlsSecret.existingSecret) }}
        - name: tls
          secret:
            secretName: {{ include "openldap.tlsSecretName" . }}
            items:
              - key: {{ .Values.tlsSecret.keys.cert }}
                path: tls.crt
              - key: {{ .Values.tlsSecret.keys.key }}
                path: tls.key
              - key: {{ .Values.tlsSecret.keys.ca }}
                path: ca.crt
        {{- end }}
        {{- if not (empty .Values.customModulesVolume) }}
        - name: custom-modules
          {{- toYaml .Values.customModulesVolume | nindent 10 }}
        {{- end }}
        {{- if not (empty .Values.customSchemasVolume) }}
        - name: custom-schemas
          {{- toYaml .Values.customSchemasVolume | nindent 10 }}
        {{- end }}
        {{- if not (empty .Values.bootstrapCustomConfigLdifVolume) }}
        - name: bootstrap-custom-config-ldif
          {{- toYaml .Values.bootstrapCustomConfigLdifVolume | nindent 10 }}
        {{- end }}
        {{- if not (empty .Values.bootstrapCustomDataLdifVolume) }}
        - name: bootstrap-custom-data-ldif
          {{- toYaml .Values.bootstrapCustomDataLdifVolume | nindent 10 }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: conf
        labels:
          {{- include "openldap.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.conf.size }}
    - metadata:
        name: data
        labels:
          {{- include "openldap.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size }}
    - metadata:
        name: backups
        labels:
          {{- include "openldap.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.backups.size }}
{{- end }}
