apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phpldapadmin.fullname" . }}-env
  labels:
    {{- include "phpldapadmin.labels" . | nindent 4 }}
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_CHANNEL: "daily"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  LDAP_CONNECTION: {{ .Values.app.ldap.connection | quote }}
  LDAP_NAME: {{ .Values.app.ldap.name | quote }}
  LDAP_HOST: {{ .Values.app.ldap.host | quote }}
  LDAP_PORT: {{ .Values.app.ldap.port | quote }}
  LDAP_SSL: {{ ternary "true" "false" .Values.app.ldap.ssl | quote }}
  LDAP_TLS: {{ ternary "true" "false" .Values.app.ldap.tls | quote }}
  LDAP_TIMEOUT: {{ .Values.app.ldap.timeout | quote }}
  LDAP_CACHE: {{ ternary "true" "false" .Values.app.ldap.cache | quote }}
  LDAP_ALERT_ROOTDN: {{ ternary "true" "false" .Values.app.ldap.alertRootDn | quote }}
