{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phpldapadmin.fullname" . }}
  labels:
    {{- include "phpldapadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ include "phpldapadmin.appKey" . | quote }}
{{- end }}
